version: '3.8'

services:
  # mysql
  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ensapay_db

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # springboot 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      - DB_HOST=mysql
      - DB_NAME=ensapay_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - phpmyadmin


volumes:
  db_data: