spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: true


server:
  port: 8081

jwt:
  secret-key: 70655367566B5970347336763979244226452948404D635166546A576D5A7164
  duration: 1440

twilio:
  account-sid: AC2e6a7c5d18e16fead92005b1369f3e58
  auth-token: 94ad0fb26c5e61ec1dd9244de5b351f4
  trial-phone-number: +12543303862