spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}?createDatabaseIfNotExist=true
        username: ${DB_USER:root}
        password: ${DB_PASSWORD}
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false


server:
    port: 8080

jwt:
    secret-key: 70655367566B5970347336763979244226452948404D635166546A576D5A7164
    duration: 1440

twilio:
    account-sid: AC2e6a7c5d18e16fead92005b1369f3e58
    auth-token: cc4fe1119de14cbd97b894521564f7ac
    trial-phone-number: +12543303862