### LOGIN AS A ADMIN
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "badusername",
  "password": "admin123"
}

### VERIFY THE TOKEN
POST http://localhost:8081/api/v1/auth/verify
Content-Type: application/json

{
    "token": "6da4589e-8929-43a4-b33f-7385350a4a5a",
    "code": "84886"
}


### ANY
POST http://
Authorization: "Bearer nnljsdgukkdigsdyfyisfd"

{}