### LOGIN AS A ADMIN
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "badusername",
  "password": "admin123"
}

### VERIFY THE TOKEN
POST http://localhost:8081/api/v1/auth/verify
Content-Type: application/json

{
    "token": "7e3b18b0-adb5-4cd3-84c9-fdb910a6e102",
    "code": "74012"
}

