### LOGIN AS A ADMIN
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "badusername",
  "password": "admin123"
}

### VERIFY THE TOKEN
POST http://localhost:8081/api/v1/auth/verify
Content-Type: application/json

{
    "token": "b4b4610f-a8a8-4350-ba5a-2c76b64eb544",
    "code": "69911"
}

